

services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        container_name: bookservice-app_book_service
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8006:80'
            - '${VITE_PORT:-5180}:${VITE_PORT:-5180}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail_book_service
        depends_on:
            - app_book_mysql
    app_book_mysql:
        image: mysql/mysql-server:8.0
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: book_service
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail_book_service
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    app_book_redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6381}:6379'
        networks:
            - sail_book_service
        volumes:
            - 'sail-redis:/data'
    app_book_phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: app_book_phpmyadmin
        environment:
            PMA_HOST: app_book_mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - '8088:80'
        depends_on:
            - app_book_mysql
        networks:
            - sail_book_service

networks:
    sail_book_service:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
